application: chromiumcodereview
version: 3
runtime: python
api_version: 1

default_expiration: 7d  # This is good for images, which never change

inbound_services:
- mail

handlers:

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
  
- url: /(robots.txt|favicon.ico)
  static_files: static/\1
  upload: static/(robots.txt|favicon.ico)

- url: /google7db36eb2cc527940.html
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /static/(script.js|styles.css|upload.py)
  static_files: static/\1
  upload: static/(script.js|styles.css|upload.py)
  expiration: 1h  # Shorter expiration, these change often

- url: /static
  static_dir: static

# Note that admin doesn't work with dasher accounts (http://b/1407477)
- url: /shell.*
  script: shell.py
  login: admin

- url: /_ah/mail/.+ 
  script: codereview/handle_incoming_email.py 
  login: admin

- url: .*
  script: main.py
